artifact_location: file:///C:/Users/prith/vr_env/Health_Prediction/mlflow_tracking/892119465647405118
creation_time: 1764836924360
experiment_id: '892119465647405118'
last_update_time: 1764836924360
lifecycle_stage: active
name: heart_disease_prediction
